spring.application.name=inno-online-store
server.port=${SERVER_PORT:8081}

spring.config.import=optional:file:.env[.properties]

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.data.redis.timeout=${REDIS_TIMEOUT}

security.jwt.token.secret-key=${JWT_SECRET}

internal.api-key=${INTERNAL_API_KEY}

spring.profiles.active=local