spring.config.activate.on-profile=docker

spring.datasource.url=${DOCKER_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=${DOCKER_REDIS_HOST}
spring.data.redis.port=${DOCKER_REDIS_PORT}
